# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.1.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _LxIfcBase
else:
    import _LxIfcBase

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _LxIfcBase.SWIG_PyInstanceMethod_New
_swig_new_static_method = _LxIfcBase.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import weakref

class SwigPyIterator(object):
    r"""Proxy of C++ swig::SwigPyIterator class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_SwigPyIterator
    value = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_value)
    incr = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_incr)
    decr = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_decr)
    distance = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_distance)
    equal = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_equal)
    copy = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_copy)
    next = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_next)
    __next__ = _swig_new_instance_method(_LxIfcBase.SwigPyIterator___next__)
    previous = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_previous)
    advance = _swig_new_instance_method(_LxIfcBase.SwigPyIterator_advance)
    __eq__ = _swig_new_instance_method(_LxIfcBase.SwigPyIterator___eq__)
    __ne__ = _swig_new_instance_method(_LxIfcBase.SwigPyIterator___ne__)
    __iadd__ = _swig_new_instance_method(_LxIfcBase.SwigPyIterator___iadd__)
    __isub__ = _swig_new_instance_method(_LxIfcBase.SwigPyIterator___isub__)
    __add__ = _swig_new_instance_method(_LxIfcBase.SwigPyIterator___add__)
    __sub__ = _swig_new_instance_method(_LxIfcBase.SwigPyIterator___sub__)
    def __iter__(self):
        return self

# Register SwigPyIterator in _LxIfcBase:
_LxIfcBase.SwigPyIterator_swigregister(SwigPyIterator)
class intP(object):
    r"""Proxy of C++ intP class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(intP self) -> intP"""
        _LxIfcBase.intP_swiginit(self, _LxIfcBase.new_intP())
    __swig_destroy__ = _LxIfcBase.delete_intP
    assign = _swig_new_instance_method(_LxIfcBase.intP_assign)
    value = _swig_new_instance_method(_LxIfcBase.intP_value)
    cast = _swig_new_instance_method(_LxIfcBase.intP_cast)
    frompointer = _swig_new_static_method(_LxIfcBase.intP_frompointer)

# Register intP in _LxIfcBase:
_LxIfcBase.intP_swigregister(intP)
intP_frompointer = _LxIfcBase.intP_frompointer

class doubleP(object):
    r"""Proxy of C++ doubleP class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(doubleP self) -> doubleP"""
        _LxIfcBase.doubleP_swiginit(self, _LxIfcBase.new_doubleP())
    __swig_destroy__ = _LxIfcBase.delete_doubleP
    assign = _swig_new_instance_method(_LxIfcBase.doubleP_assign)
    value = _swig_new_instance_method(_LxIfcBase.doubleP_value)
    cast = _swig_new_instance_method(_LxIfcBase.doubleP_cast)
    frompointer = _swig_new_static_method(_LxIfcBase.doubleP_frompointer)

# Register doubleP in _LxIfcBase:
_LxIfcBase.doubleP_swigregister(doubleP)
doubleP_frompointer = _LxIfcBase.doubleP_frompointer

class boolP(object):
    r"""Proxy of C++ boolP class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(boolP self) -> boolP"""
        _LxIfcBase.boolP_swiginit(self, _LxIfcBase.new_boolP())
    __swig_destroy__ = _LxIfcBase.delete_boolP
    assign = _swig_new_instance_method(_LxIfcBase.boolP_assign)
    value = _swig_new_instance_method(_LxIfcBase.boolP_value)
    cast = _swig_new_instance_method(_LxIfcBase.boolP_cast)
    frompointer = _swig_new_static_method(_LxIfcBase.boolP_frompointer)

# Register boolP in _LxIfcBase:
_LxIfcBase.boolP_swigregister(boolP)
boolP_frompointer = _LxIfcBase.boolP_frompointer

import Base
SHARED_PTR_DISOWN = _LxIfcBase.SHARED_PTR_DISOWN

class LxIfcProperty(object):
    r"""Proxy of C++ LxIfcBase::LxIfcProperty class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    Type_UNKOWN = _LxIfcBase.LxIfcProperty_Type_UNKOWN
    
    Type_STRING = _LxIfcBase.LxIfcProperty_Type_STRING
    
    Type_BOOL = _LxIfcBase.LxIfcProperty_Type_BOOL
    
    Type_INTEGER = _LxIfcBase.LxIfcProperty_Type_INTEGER
    
    Type_DOUBLE = _LxIfcBase.LxIfcProperty_Type_DOUBLE
    
    Type_LOGICAL = _LxIfcBase.LxIfcProperty_Type_LOGICAL
    
    Type_ENUM = _LxIfcBase.LxIfcProperty_Type_ENUM
    

    def __init__(self, *args):
        r"""
        __init__(LxIfcProperty self) -> LxIfcProperty
        __init__(LxIfcProperty self, String aKey) -> LxIfcProperty
        __init__(LxIfcProperty self, String aKey, String aValue) -> LxIfcProperty
        __init__(LxIfcProperty self, String aKey, String aValue, LxIfcBase::LxIfcProperty::Type const & aType) -> LxIfcProperty
        """
        _LxIfcBase.LxIfcProperty_swiginit(self, _LxIfcBase.new_LxIfcProperty(*args))
    addProperty = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_addProperty)
    removeProperty = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_removeProperty)
    getPropertyByKey = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_getPropertyByKey)
    getProperties = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_getProperties)
    isEmpty = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_isEmpty)
    setKey = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_setKey)
    getKey = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_getKey)
    setValue = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_setValue)
    getValue = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_getValue)
    setType = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_setType)
    getType = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_getType)
    getTypeAsString = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_getTypeAsString)
    addEnumReference = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_addEnumReference)
    getEnumReference = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_getEnumReference)
    setExpandedByDefault = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_setExpandedByDefault)
    isExpandedByDefault = _swig_new_instance_method(_LxIfcBase.LxIfcProperty_isExpandedByDefault)
    __swig_destroy__ = _LxIfcBase.delete_LxIfcProperty

# Register LxIfcProperty in _LxIfcBase:
_LxIfcBase.LxIfcProperty_swigregister(LxIfcProperty)
class LxIfcModel(object):
    r"""Proxy of C++ LxIfcBase::LxIfcModel class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_LxIfcModel
    IFC_VERSION_UNDEFINED = _LxIfcBase.LxIfcModel_IFC_VERSION_UNDEFINED
    
    IFC_VERSION_UNKNOWN = _LxIfcBase.LxIfcModel_IFC_VERSION_UNKNOWN
    
    IFC2X = _LxIfcBase.LxIfcModel_IFC2X
    
    IFC2X2 = _LxIfcBase.LxIfcModel_IFC2X2
    
    IFC2X3 = _LxIfcBase.LxIfcModel_IFC2X3
    
    IFC2X4 = _LxIfcBase.LxIfcModel_IFC2X4
    
    IFC4 = _LxIfcBase.LxIfcModel_IFC4
    
    IFC4X1 = _LxIfcBase.LxIfcModel_IFC4X1
    
    IFC4X2 = _LxIfcBase.LxIfcModel_IFC4X2
    
    IFC4X3 = _LxIfcBase.LxIfcModel_IFC4X3
    
    IFC5 = _LxIfcBase.LxIfcModel_IFC5
    
    getIfcSchemaVersionString = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIfcSchemaVersionString)
    m_ifc_schema_version = property(_LxIfcBase.LxIfcModel_m_ifc_schema_version_get, _LxIfcBase.LxIfcModel_m_ifc_schema_version_set, doc=r"""m_ifc_schema_version : LxIfcBase::LxIfcModel::LxIfcSchemaVersion""")
    m_ifc_header_filename = property(_LxIfcBase.LxIfcModel_m_ifc_header_filename_get, _LxIfcBase.LxIfcModel_m_ifc_header_filename_set, doc=r"""m_ifc_header_filename : LxIfcBase::LxIfcModel::LxIfcHeaderFilename""")
    getIfcSchemaVersion = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIfcSchemaVersion)
    getIfcHeaderFileName = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIfcHeaderFileName)
    getFileHeader = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getFileHeader)
    getFileDescription = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getFileDescription)
    getFileName = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getFileName)
    getLengthUnitFactor = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getLengthUnitFactor)
    getPlaneAngleUnitFactor = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getPlaneAngleUnitFactor)
    setIfcSchemaVersion = _swig_new_instance_method(_LxIfcBase.LxIfcModel_setIfcSchemaVersion)
    setFileHeader = _swig_new_instance_method(_LxIfcBase.LxIfcModel_setFileHeader)
    setFileDescription = _swig_new_instance_method(_LxIfcBase.LxIfcModel_setFileDescription)
    setFileName = _swig_new_instance_method(_LxIfcBase.LxIfcModel_setFileName)
    resolveInverseAttributes = _swig_new_instance_method(_LxIfcBase.LxIfcModel_resolveInverseAttributes)
    clearIfcModel = _swig_new_instance_method(_LxIfcBase.LxIfcModel_clearIfcModel)
    initIfcModel = _swig_new_instance_method(_LxIfcBase.LxIfcModel_initIfcModel)
    resetIfcModel = _swig_new_instance_method(_LxIfcBase.LxIfcModel_resetIfcModel)
    updateCache = _swig_new_instance_method(_LxIfcBase.LxIfcModel_updateCache)
    clearCache = _swig_new_instance_method(_LxIfcBase.LxIfcModel_clearCache)
    initFileHeader = _swig_new_instance_method(_LxIfcBase.LxIfcModel_initFileHeader)
    updateFileHeader = _swig_new_instance_method(_LxIfcBase.LxIfcModel_updateFileHeader)
    getMapIIfcEntities = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getMapIIfcEntities)
    getIIfcEntityById = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIIfcEntityById)
    getIIfcEntityByGUID = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIIfcEntityByGUID)
    getIIfcRootByGUID = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIIfcRootByGUID)
    getIIfcRootMap = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIIfcRootMap)
    getIIfcEntityTypeMap = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getIIfcEntityTypeMap)
    getPropertiesFromEntity = _swig_new_instance_method(_LxIfcBase.LxIfcModel_getPropertiesFromEntity)
    setIfcHeaderFileName = _swig_new_instance_method(_LxIfcBase.LxIfcModel_setIfcHeaderFileName)
    force2d = property(_LxIfcBase.LxIfcModel_force2d_get, _LxIfcBase.LxIfcModel_force2d_set, doc=r"""force2d : std::unordered_set<(std::string)>""")

# Register LxIfcModel in _LxIfcBase:
_LxIfcBase.LxIfcModel_swigregister(LxIfcModel)
class LxIfcReadResult(object):
    r"""Proxy of C++ LxIfcBase::LxIfcReadResult class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    isOK = property(_LxIfcBase.LxIfcReadResult_isOK_get, _LxIfcBase.LxIfcReadResult_isOK_set, doc=r"""isOK : bool""")
    FileName = property(_LxIfcBase.LxIfcReadResult_FileName_get, _LxIfcBase.LxIfcReadResult_FileName_set, doc=r"""FileName : Base::String""")
    SchemaNameEnum = property(_LxIfcBase.LxIfcReadResult_SchemaNameEnum_get, _LxIfcBase.LxIfcReadResult_SchemaNameEnum_set, doc=r"""SchemaNameEnum : LxIfcBase::SchemaName""")
    SchemaName = property(_LxIfcBase.LxIfcReadResult_SchemaName_get, _LxIfcBase.LxIfcReadResult_SchemaName_set, doc=r"""SchemaName : Base::String""")
    SchemaNameLongForm = property(_LxIfcBase.LxIfcReadResult_SchemaNameLongForm_get, _LxIfcBase.LxIfcReadResult_SchemaNameLongForm_set, doc=r"""SchemaNameLongForm : Base::String""")
    Name = property(_LxIfcBase.LxIfcReadResult_Name_get, _LxIfcBase.LxIfcReadResult_Name_set, doc=r"""Name : Base::String""")
    TimeStamp = property(_LxIfcBase.LxIfcReadResult_TimeStamp_get, _LxIfcBase.LxIfcReadResult_TimeStamp_set, doc=r"""TimeStamp : Base::String""")
    Author = property(_LxIfcBase.LxIfcReadResult_Author_get, _LxIfcBase.LxIfcReadResult_Author_set, doc=r"""Author : Base::String""")
    Organization = property(_LxIfcBase.LxIfcReadResult_Organization_get, _LxIfcBase.LxIfcReadResult_Organization_set, doc=r"""Organization : Base::String""")
    PreprocessorVersion = property(_LxIfcBase.LxIfcReadResult_PreprocessorVersion_get, _LxIfcBase.LxIfcReadResult_PreprocessorVersion_set, doc=r"""PreprocessorVersion : Base::String""")
    OriginatingSystem = property(_LxIfcBase.LxIfcReadResult_OriginatingSystem_get, _LxIfcBase.LxIfcReadResult_OriginatingSystem_set, doc=r"""OriginatingSystem : Base::String""")
    Authorisation = property(_LxIfcBase.LxIfcReadResult_Authorisation_get, _LxIfcBase.LxIfcReadResult_Authorisation_set, doc=r"""Authorisation : Base::String""")
    FileDescription = property(_LxIfcBase.LxIfcReadResult_FileDescription_get, _LxIfcBase.LxIfcReadResult_FileDescription_set, doc=r"""FileDescription : Base::String""")
    Description = property(_LxIfcBase.LxIfcReadResult_Description_get, _LxIfcBase.LxIfcReadResult_Description_set, doc=r"""Description : Base::String""")
    ImplementationLevel = property(_LxIfcBase.LxIfcReadResult_ImplementationLevel_get, _LxIfcBase.LxIfcReadResult_ImplementationLevel_set, doc=r"""ImplementationLevel : Base::String""")
    ErrorCode = property(_LxIfcBase.LxIfcReadResult_ErrorCode_get, _LxIfcBase.LxIfcReadResult_ErrorCode_set, doc=r"""ErrorCode : int""")
    ErrorMsg = property(_LxIfcBase.LxIfcReadResult_ErrorMsg_get, _LxIfcBase.LxIfcReadResult_ErrorMsg_set, doc=r"""ErrorMsg : Base::String""")

    def __init__(self):
        r"""__init__(LxIfcReadResult self) -> LxIfcReadResult"""
        _LxIfcBase.LxIfcReadResult_swiginit(self, _LxIfcBase.new_LxIfcReadResult())
    __swig_destroy__ = _LxIfcBase.delete_LxIfcReadResult

# Register LxIfcReadResult in _LxIfcBase:
_LxIfcBase.LxIfcReadResult_swigregister(LxIfcReadResult)
IFC_LOGICAL_TRUE = _LxIfcBase.IFC_LOGICAL_TRUE

IFC_LOGICAL_FALSE = _LxIfcBase.IFC_LOGICAL_FALSE

IFC_LOGICAL_UNKNOWN = _LxIfcBase.IFC_LOGICAL_UNKNOWN

class LxIfcEntity(object):
    r"""Proxy of C++ LxIfcBase::LxIfcEntity class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_LxIfcEntity
    getId = _swig_new_instance_method(_LxIfcBase.LxIfcEntity_getId)
    getEntityType = _swig_new_instance_method(_LxIfcBase.LxIfcEntity_getEntityType)

# Register LxIfcEntity in _LxIfcBase:
_LxIfcBase.LxIfcEntity_swigregister(LxIfcEntity)
class IIfcRoot(object):
    r"""Proxy of C++ LxIfcBase::IIfcRoot class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcRoot
    getGlobalId = _swig_new_instance_method(_LxIfcBase.IIfcRoot_getGlobalId)
    getName = _swig_new_instance_method(_LxIfcBase.IIfcRoot_getName)
    getId = _swig_new_instance_method(_LxIfcBase.IIfcRoot_getId)

# Register IIfcRoot in _LxIfcBase:
_LxIfcBase.IIfcRoot_swigregister(IIfcRoot)
class IIfcProject(object):
    r"""Proxy of C++ LxIfcBase::IIfcProject class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcProject

    def __init__(self):
        r"""__init__(IIfcProject self) -> IIfcProject"""
        _LxIfcBase.IIfcProject_swiginit(self, _LxIfcBase.new_IIfcProject())

# Register IIfcProject in _LxIfcBase:
_LxIfcBase.IIfcProject_swigregister(IIfcProject)
class IIfcProduct(object):
    r"""Proxy of C++ LxIfcBase::IIfcProduct class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcProduct

    def __init__(self):
        r"""__init__(IIfcProduct self) -> IIfcProduct"""
        _LxIfcBase.IIfcProduct_swiginit(self, _LxIfcBase.new_IIfcProduct())

# Register IIfcProduct in _LxIfcBase:
_LxIfcBase.IIfcProduct_swigregister(IIfcProduct)
class IIfcOwnerHistory(object):
    r"""Proxy of C++ LxIfcBase::IIfcOwnerHistory class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcOwnerHistory

    def __init__(self):
        r"""__init__(IIfcOwnerHistory self) -> IIfcOwnerHistory"""
        _LxIfcBase.IIfcOwnerHistory_swiginit(self, _LxIfcBase.new_IIfcOwnerHistory())

# Register IIfcOwnerHistory in _LxIfcBase:
_LxIfcBase.IIfcOwnerHistory_swigregister(IIfcOwnerHistory)
class IIfcMaterialSelect(object):
    r"""Proxy of C++ LxIfcBase::IIfcMaterialSelect class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcMaterialSelect

    def __init__(self):
        r"""__init__(IIfcMaterialSelect self) -> IIfcMaterialSelect"""
        _LxIfcBase.IIfcMaterialSelect_swiginit(self, _LxIfcBase.new_IIfcMaterialSelect())

# Register IIfcMaterialSelect in _LxIfcBase:
_LxIfcBase.IIfcMaterialSelect_swigregister(IIfcMaterialSelect)
class IIfcMaterial(object):
    r"""Proxy of C++ LxIfcBase::IIfcMaterial class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcMaterial

    def __init__(self):
        r"""__init__(IIfcMaterial self) -> IIfcMaterial"""
        _LxIfcBase.IIfcMaterial_swiginit(self, _LxIfcBase.new_IIfcMaterial())

# Register IIfcMaterial in _LxIfcBase:
_LxIfcBase.IIfcMaterial_swigregister(IIfcMaterial)
class IIfcGeometricRepresentationItem(object):
    r"""Proxy of C++ LxIfcBase::IIfcGeometricRepresentationItem class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcGeometricRepresentationItem

    def __init__(self):
        r"""__init__(IIfcGeometricRepresentationItem self) -> IIfcGeometricRepresentationItem"""
        _LxIfcBase.IIfcGeometricRepresentationItem_swiginit(self, _LxIfcBase.new_IIfcGeometricRepresentationItem())

# Register IIfcGeometricRepresentationItem in _LxIfcBase:
_LxIfcBase.IIfcGeometricRepresentationItem_swigregister(IIfcGeometricRepresentationItem)
class IIfcGeometricRepresentationContext(object):
    r"""Proxy of C++ LxIfcBase::IIfcGeometricRepresentationContext class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcGeometricRepresentationContext

    def __init__(self):
        r"""__init__(IIfcGeometricRepresentationContext self) -> IIfcGeometricRepresentationContext"""
        _LxIfcBase.IIfcGeometricRepresentationContext_swiginit(self, _LxIfcBase.new_IIfcGeometricRepresentationContext())

# Register IIfcGeometricRepresentationContext in _LxIfcBase:
_LxIfcBase.IIfcGeometricRepresentationContext_swigregister(IIfcGeometricRepresentationContext)
class IIfcElement(object):
    r"""Proxy of C++ LxIfcBase::IIfcElement class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcElement

    def __init__(self):
        r"""__init__(IIfcElement self) -> IIfcElement"""
        _LxIfcBase.IIfcElement_swiginit(self, _LxIfcBase.new_IIfcElement())

# Register IIfcElement in _LxIfcBase:
_LxIfcBase.IIfcElement_swigregister(IIfcElement)
class IIfcCdwkElement(object):
    r"""Proxy of C++ LxIfcBase::IIfcCdwkElement class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _LxIfcBase.delete_IIfcCdwkElement

    def __init__(self):
        r"""__init__(IIfcCdwkElement self) -> IIfcCdwkElement"""
        _LxIfcBase.IIfcCdwkElement_swiginit(self, _LxIfcBase.new_IIfcCdwkElement())

# Register IIfcCdwkElement in _LxIfcBase:
_LxIfcBase.IIfcCdwkElement_swigregister(IIfcCdwkElement)
class vector_IfcProperty(object):
    r"""Proxy of C++ std::vector< std::shared_ptr< LxIfcBase::LxIfcProperty > > class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    iterator = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_iterator)
    def __iter__(self):
        return self.iterator()
    __nonzero__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___nonzero__)
    __bool__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___bool__)
    __len__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___len__)
    __getslice__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___getslice__)
    __setslice__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___setslice__)
    __delslice__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___delslice__)
    __delitem__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___delitem__)
    __getitem__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___getitem__)
    __setitem__ = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty___setitem__)
    pop = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_pop)
    append = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_append)
    empty = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_empty)
    size = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_size)
    swap = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_swap)
    begin = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_begin)
    end = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_end)
    rbegin = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_rbegin)
    rend = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_rend)
    clear = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_clear)
    get_allocator = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_get_allocator)
    pop_back = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_pop_back)
    erase = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_erase)

    def __init__(self, *args):
        r"""
        __init__(vector_IfcProperty self) -> vector_IfcProperty
        __init__(vector_IfcProperty self, vector_IfcProperty other) -> vector_IfcProperty
        __init__(vector_IfcProperty self, std::vector< std::shared_ptr< LxIfcBase::LxIfcProperty > >::size_type size) -> vector_IfcProperty
        __init__(vector_IfcProperty self, std::vector< std::shared_ptr< LxIfcBase::LxIfcProperty > >::size_type size, std::vector< std::shared_ptr< LxIfcBase::LxIfcProperty > >::value_type const & value) -> vector_IfcProperty
        """
        _LxIfcBase.vector_IfcProperty_swiginit(self, _LxIfcBase.new_vector_IfcProperty(*args))
    push_back = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_push_back)
    front = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_front)
    back = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_back)
    assign = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_assign)
    resize = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_resize)
    insert = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_insert)
    reserve = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_reserve)
    capacity = _swig_new_instance_method(_LxIfcBase.vector_IfcProperty_capacity)
    __swig_destroy__ = _LxIfcBase.delete_vector_IfcProperty

# Register vector_IfcProperty in _LxIfcBase:
_LxIfcBase.vector_IfcProperty_swigregister(vector_IfcProperty)

